"""
Test User Authentication
Tests the User class for registration and login
"""

from user import User

print("="*70)
print("USER AUTHENTICATION TESTS")
print("="*70)

# ============================================================================
# TEST 1: Register a new student
# ============================================================================
print("\n--- TEST 1: Register a new student ---")

# Create a User object (in memory, not in database yet)
student = User(
    username="jsmith",
    email="john.smith@school.edu",
    password="mypassword",  # Plain text - will be hashed automatically
    first_name="John",
    last_name="Smith",
    role="student",
    grad_year=2025
)

# Save to database
if student.save():
    print(f"✓ Student created successfully!")
    print(f"  User ID: {student.user_id}")  # Auto-generated by database
    print(f"  Username: {student.username}")
    print(f"  Name: {student.first_name} {student.last_name}")
    print(f"  Role: {student.role}")
else:
    print(f"✗ Failed to create student")


# ============================================================================
# TEST 2: Register a teacher
# ============================================================================
print("\n--- TEST 2: Register a teacher ---")

teacher = User(
    username="msjones",
    email="sarah.jones@school.edu",
    password="teacher123",
    first_name="Sarah",
    last_name="Jones",
    role="teacher",
    department="Visual Arts"
)

if teacher.save():
    print(f"✓ Teacher created successfully!")
    print(f"  Username: {teacher.username}")
    print(f"  Department: {teacher.department}")
else:
    print(f"✗ Failed to create teacher")


# ============================================================================
# TEST 3: Try to create duplicate username (should fail)
# ============================================================================
print("\n--- TEST 3: Try to create duplicate username ---")

duplicate = User(
    username="jsmith",  # Same username as Test 1!
    email="different@school.edu",
    password="password",
    first_name="Fake",
    last_name="User",
    role="student"
)

if duplicate.save():
    print(f"✗ ERROR: Should not have allowed duplicate username!")
else:
    print(f"✓ Correctly rejected duplicate username")


# ============================================================================
# TEST 4: Load user from database
# ============================================================================
print("\n--- TEST 4: Load user from database ---")

# Load the student we created in Test 1
loaded_user = User.load_by_username("jsmith")

if loaded_user:
    print(f"✓ User loaded successfully!")
    print(f"  {loaded_user}")  # Uses __str__ method
    print(f"  Email: {loaded_user.email}")
    print(f"  Created: {loaded_user.created_at}")
else:
    print(f"✗ User not found")


# ============================================================================
# TEST 5: Login with CORRECT password
# ============================================================================
print("\n--- TEST 5: Login with CORRECT password ---")

user = User.load_by_username("jsmith")
if user:
    if user.login("mypassword"):  # Correct password
        print(f"✓ Login successful!")
        print(f"  Welcome {user.first_name} {user.last_name}!")
    else:
        print(f"✗ Login failed (wrong password)")
else:
    print(f"✗ User not found")


# ============================================================================
# TEST 6: Login with WRONG password
# ============================================================================
print("\n--- TEST 6: Login with WRONG password ---")

user = User.load_by_username("jsmith")
if user:
    if user.login("wrongpassword"):  # Wrong password!
        print(f"✗ ERROR: Should not have logged in with wrong password!")
    else:
        print(f"✓ Correctly rejected wrong password")
else:
    print(f"✗ User not found")


# ============================================================================
# TEST 7: Update user profile
# ============================================================================
print("\n--- TEST 7: Update user profile ---")

user = User.load_by_username("jsmith")
if user:
    print(f"  Before: Email = {user.email}")
    
    # Update email
    if user.update_profile(email="john.new@school.edu"):
        print(f"✓ Profile updated successfully!")
        print(f"  After: Email = {user.email}")
        
        # Verify it saved to database
        reloaded = User.load_by_username("jsmith")
        print(f"  From DB: Email = {reloaded.email}")
    else:
        print(f"✗ Failed to update profile")


# ============================================================================
# TEST 8: Logout
# ============================================================================
print("\n--- TEST 8: Logout ---")

user = User.load_by_username("jsmith")
if user:
    user.logout()


# ============================================================================
# TEST 9: Login with non-existent user
# ============================================================================
print("\n--- TEST 9: Login with non-existent user ---")

fake_user = User.load_by_username("doesnotexist")
if fake_user is None:
    print(f"✓ Correctly returned None for non-existent user")
else:
    print(f"✗ ERROR: Should have returned None")


print("\n" + "="*70)
print("ALL TESTS COMPLETE!")
print("="*70)